services:
    tee:
        command: ["pnpm", "start", "non-interactive"]
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
            - tee:/app/packages/client-twitter/src/tweetcache
            - tee:/app/db.sqlite
        environment:
            - OPENAI_API_KEY
            - TWITTER_DRY_RUN=false
            - TWITTER_USERNAME
            - TWITTER_PASSWORD
            - TWITTER_EMAIL
            - POST_INTERVAL_MIN
            - POST_INTERVAL_MAX
            - X_SERVER_URL=https://api.red-pill.ai/v1
            - BIRDEYE_API_KEY=
            - SOL_ADDRESS=So11111111111111111111111111111111111111112
            - SLIPPAGE=1
            - RPC_URL=https://api.mainnet-beta.solana.com
            - HELIUS_API_KEY=
            - SERVER_PORT=3000
            - WALLET_SECRET_SALT=secret_salt
        ports:
            - "3000:80"
        restart: always

volumes:
    tee:
